// Generated with carray.sh from /home/yangxin/xs-env/keystone/sm/plat/generic/platform_override_modules.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <platform_override.h>


const struct platform_override *const platform_override_modules[] = {
	NULL
};
