// Generated with carray.sh from /home/yangxin/xs-env/keystone/sm/opensbi/lib/utils/fdt/fdt_early_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/fdt/fdt_driver.h>

extern const struct fdt_driver fdt_reset_htif;
extern const struct fdt_driver fdt_ipi_mswi;

const struct fdt_driver *const fdt_early_drivers[] = {
	&fdt_reset_htif,
	&fdt_ipi_mswi,
	NULL
};
