// Generated with carray.sh from /home/yangxin/xs-env/keystone/sm/opensbi/lib/utils/timer/fdt_timer_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/timer/fdt_timer.h>

extern const struct fdt_driver fdt_timer_mtimer;

const struct fdt_driver *const fdt_timer_drivers[] = {
	&fdt_timer_mtimer,
	NULL
};
