// Generated with carray.sh from /home/yangxin/xs-env/keystone/sm/opensbi/lib/utils/serial/fdt_serial_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/serial/fdt_serial.h>

extern const struct fdt_driver fdt_serial_uart8250;

const struct fdt_driver *const fdt_serial_drivers[] = {
	&fdt_serial_uart8250,
	NULL
};
