// Generated with carray.sh from /home/yangxin/xs-env/keystone/sm/opensbi/lib/utils/irqchip/fdt_irqchip_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/irqchip/fdt_irqchip.h>

extern const struct fdt_driver fdt_irqchip_aplic;
extern const struct fdt_driver fdt_irqchip_imsic;

const struct fdt_driver *const fdt_irqchip_drivers[] = {
	&fdt_irqchip_aplic,
	&fdt_irqchip_imsic,
	NULL
};
